name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        java-package: 'jdk'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Prepare deployment package
      run: |
        mkdir -p deploy
        cp build/libs/*.jar deploy/
        echo "web: java -jar *.jar" > deploy/Procfile

    - name: Compress deployment package
      run: zip -r app.zip deploy/*

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD_HH-mm-ss
        utcOffset: "+09:00"

    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_EB_REGION }}
        application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
        version_label: v${{steps.current-time.outputs.formattedTime}}-${{ github.run_number }}
        deployment_package: app.zip
